.travis.yml

Fix travis build for semantic versioning

Update tekton sdk

---

.travis.yml

small change to test auto sem ver process

fix(semver): small change to test auto sem ver process

---

README.md

Add version to readme to fix sem ver build issue

chore(fix readme): add version to readme to fix sem ver build issue

---

examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Signed-off-by: Brian Gleeson <brian.gleeson@ie.ibm.com>
Latest updates to match the v2 Tekton Pipeline APIs

feat(tekton): update for latest v2 tekton APIs

---

examples/test_cd_toolchain_v2_examples.py
ibm_continuous_delivery/cd_toolchain_v2.py
test/integration/test_cd_toolchain_v2.py
test/unit/test_cd_toolchain_v2.py

Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Added toolchain python SDK

feat(toolchain): add toolchain python SDK

---

ibm_continuous_delivery/cd_toolchain_v2.py
test/unit/test_cd_toolchain_v2.py

Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Removed `tags` property from toolchain SDK

remove 'tags' from toolchain SDK

---

examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Signed-off-by: Brian Gleeson <brian.gleeson@ie.ibm.com>
Remove offset option when fetching pipeline runs. Remove default values for booleans in PATCH requests

fix(tekton): remove offset and patch defaults

---

README.md
ibm_continuous_delivery/__init__.py

Signed-off-by: Omar Al Bastami <omar.albastami@ibm.com>
Adding missing toolchain import in __init__.py, along with missing README documentation

fix(toolchain): add missing toolchain import

---

.gitignore
.travis.yml
examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
package.json
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

The supporting Tekton Pipeline V2 APIs have been udpated after their GA with some minor fixes/changes. Sync the python-sdk to match the updates
These API updates are not likely to be deployed to production until the new year (Jan 2023)

Tekton updates after the V2 API GA

---

README.md

Signed-off-by: Brian Gleeson <brian.gleeson@ie.ibm.com>
Fix readme links so that it opens the correct code option in the docs

chore(readme): fix links

---

examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Signed-off-by: Brian Gleeson <brian.gleeson@ie.ibm.com>
Make hrefs not required in a number of places, and use WorkerIdentity instead of Worker for creation

fix(tekton): WorkerIdentity and hrefs updated

---

README.md

Address feedback from Phil Adams to correct the module and import table. Also fix up the TOC and add some extra python shields

chore(doc): fix readme issues

---

README.md

BREAKING CHANGE: release v1.0.0
Release v1.0.0

feat(build): trigger major version build

---

.travis.yml
README.md
requirements.txt

Update SDK according to changes from the template repo

fix: sync with template repo

---

examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add support for `next_build_number` property in Tekton Pipelines

feat(tekton): add next build number support

---

.secrets.baseline

Dummy values in test/example files are being marked as false positives in detect-secrets script. Exclude them from the scans.

build: update secrets baseline

---

requirements.txt

build: bump core dependency

---

requirements.txt

Bumps the python core dependency to the latest version (3.16.7).

build: bump python core to latest (3.16.7)

---

examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/integration/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add support for favorite triggers in Tekton pipeline
Also includes some minor documentation updates

Trigger favorite

---

.travis.yml

Fixes gpg errors in travis builds

build: avoid GPG errors in travis builds

---

examples/test_cd_toolchain_v2_examples.py
ibm_continuous_delivery/cd_toolchain_v2.py
test/integration/test_cd_toolchain_v2.py
test/unit/test_cd_toolchain_v2.py

Supporting `name` parameter when retrieving toolchain collection

feat(toolchain): add name query param to list toolchains

---

.secrets.baseline
examples/test_cd_toolchain_v2_examples.py
ibm_continuous_delivery/cd_toolchain_v2.py
test/integration/test_cd_toolchain_v2.py
test/unit/test_cd_toolchain_v2.py

feat(toolchain): add eu-es region

---

ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

feat(tekton): add eu-es region

---

.secrets.baseline
examples/test_cd_toolchain_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
ibm_continuous_delivery/cd_toolchain_v2.py
test/integration/test_cd_toolchain_v2.py
test/unit/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_toolchain_v2.py

feat: support eu-es region

---

.travis.yml
examples/test_cd_tekton_pipeline_v2_examples.py
ibm_continuous_delivery/cd_tekton_pipeline_v2.py
ibm_continuous_delivery/version.py
requirements.txt
test/unit/test_cd_tekton_pipeline_v2.py
test/unit/test_cd_toolchain_v2.py

Add support for locked properties in Tekton pipelines and triggers.
Added miscellaneous updates copied from the node-sdk-template, and generated with a newer version of the SDK generator, hence there's a lot of other changes included

feat(tekton): locked property support

---

ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add support for CEL filtering of Git triggers in tekton pipeline

feat(tekton): Add support for CEL filtering

---

ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add option to enable/disable fork events in git triggers

feat(tekton): Add fork events option

---

ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add full support for the "enable events from forks" feature to Tekton Git triggers

feat(tekton): more fork property support

---

.pylintrc
.travis.yml
README.md
pyproject.toml

Bump python to 3.9 in the project, so that the minimum version is 3.9 and the maximum is the latest which is 3.13. And update some other packages to match the latest from the python-sdk-template

fix: bump python and packages

---

ibm_continuous_delivery/cd_toolchain_v2.py
test/unit/test_cd_toolchain_v2.py

fix: add ca-mon support to toolchains

---

ibm_continuous_delivery/cd_tekton_pipeline_v2.py
test/unit/test_cd_tekton_pipeline_v2.py

Add support for the disable_draft_events option on Git triggers

fix: add draft PR events option support
